<?php 
 return array (
  'CLOUD_USERNAME' => '',
  'CLOUD_PASSWORD' => '',
  'COOKIE_EXPIRE' => '3600',
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'SESSION_PREFIX' => '',
  'SESSION_OPTIONS' => 
  array (
    'domain' => '',
  ),
  'SHOW_ERROR_MSG' => '0',
  'ERROR_MESSAGE' => '您浏览的页面暂时发生了错误！请稍后再试～',
  'ERROR_PAGE' => '',
  'URL_CASE_INSENSITIVE' => false,
  'URL_MODEL' => 0,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '.html',
  'TOKEN_ON' => false,
  'TOKEN_NAME' => '__hash__',
  'TOKEN_TYPE' => 'md5',
  'PAGE_LISTROWS' => '20',
  'VAR_PAGE' => 'page',
  'PAGE_TEMPLATE' => '<span class="all">共有{recordcount}条信息</span><span class="pageindex">{pageindex}/{pagecount}</span>{first}{prev}{liststart}{list}{listend}{next}{last}',
  'DEFAULT_MODULE' => 'Content',
  'DEFAULT_TIMEZONE' => 'PRC',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'DEFAULT_FILTER' => 'htmlspecialchars',
  'DEFAULT_LANG' => 'zh-cn',
  'DATA_CACHE_TYPE' => 'File',
  'DATA_CACHE_SUBDIR' => '0',
  'LOAD_EXT_FILE' => 'extend',
  'DEFAULT_GROUP' => 'Contents',
  'CLOUD_ON' => false,
);